env:
  browser: true
  es2021: true
  jest/globals: true
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./tsconfig.json"
  sourceType: "module"
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
root: true
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - jest
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - next
  - next/core-web-vitals
  - prettier
